//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QFramework.Example
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    // Generate Id:4c404f9f-8c98-49e7-ac78-542cff46b03b
    public partial class UIHomePanel
    {
        
        public const string NAME = "UIHomePanel";
        
        [SerializeField()]
        public UnityEngine.RectTransform StartPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button startBtn;
        
        [SerializeField()]
        public UnityEngine.RectTransform TipsPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Text moneyText;
        
        [SerializeField()]
        public UnityEngine.UI.Text targetMoney;
        
        [SerializeField()]
        public UnityEngine.UI.Text timeText;
        
        [SerializeField()]
        public UnityEngine.UI.Text levelText;
        
        [SerializeField()]
        public UnityEngine.RectTransform boomGird;
        
        [SerializeField()]
        public UnityEngine.RectTransform setPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button cheatBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button restBtn;
        
        [SerializeField()]
        public UnityEngine.UI.Button quitBtn;
        
        [SerializeField()]
        public UnityEngine.RectTransform endPanel;
        
        [SerializeField()]
        public UnityEngine.RectTransform switchPanel;
        
        [SerializeField()]
        public UnityEngine.UI.Button switchBtn;
        
        [SerializeField()]
        public UnityEngine.RectTransform fractionPoint;
        
        private UIHomePanelData mPrivateData = null;
        
        public UIHomePanelData Data
        {
            get
            {
                return mData;
            }
        }
        
        UIHomePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new UIHomePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            StartPanel = null;
            startBtn = null;
            TipsPanel = null;
            moneyText = null;
            targetMoney = null;
            timeText = null;
            levelText = null;
            boomGird = null;
            setPanel = null;
            cheatBtn = null;
            restBtn = null;
            quitBtn = null;
            endPanel = null;
            switchPanel = null;
            switchBtn = null;
            fractionPoint = null;
            mData = null;
        }
    }
}
