//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Prefabs
    {
        public const string BundleName = "prefabs";
        public const string BOOMOBJ = "boomobj";
        public const string BOOMUI = "boomui";
        public const string DIAMONDS = "diamonds";
        public const string EXPLOSIVE = "explosive";
        public const string FRACTIONTEXT = "fractiontext";
        public const string GOLD = "gold";
        public const string GOLDTWO = "goldtwo";
        public const string POTION = "potion";
        public const string STONEONE = "stoneone";
        public const string STONETWO = "stonetwo";
    }
}
